language: elixir
elixir:
- 1.3.2
otp_release:
- 19.0
addons:
  postgresql: '9.4'
before_script:
- mix ecto.create
deploy:
  provider: heroku
  on: develop
  api_key:
    secure: nJGvSbSJeWLEMenm5GYjKlQpqxsu3oQbdVff/Q2F3GugTb5ee0SZ3JpiYNKm+7kXpWl0BnW1ddebPdgiim3Fv6RQ3iAQUiP/t9t6DsCGyQuFktzjDD2neb6CcFR5mGgM12vD37+jXMWe0aRK5ARzIRAKYXlPcgNG7le4cgGYwB6Ffe/H2LCyddM/0q4wagUn9GLoxlt2doNSyVAYf6yJED4PcZdf9Ma74AY3642dUhjM43CdBYjsEOFDodxut2PWVAYLlq9VRvRu1RjsuTE+xhhiuR1w7Fv75R6Jo8hN3ul1XF43sbKhzzIzIA62ZIXN+VOOwZsPAgtZHoKRh7BA0gLRUPlYTVl1/tb77E0wvt26KnmX1TCggEI+Hp5Pqiq6IvBRu16qGfbs+F3c77uzeypGkmV073rxW4ZU5I9iB67s2VxG2/mvtRKnMN78qDF9eHvOwWtXGcbTvyYMghusiDzjpYFx8FiLpEnMMG0AHHVtNscQF4dPXspp6AIy3mVpPXuGBky9hNUL7n31GJNdI+8vl9PbTE14kX++Qrw0NcITPs+4DkmK0QYIfdWYA6eSiPgbqASuWwuOJtWR+gxYJcTvNnC7FPHBrw1QH38sTfllVj7QVdoCiGOEb9uUjha7NW/Fs1zOxZxOFmEX+by6cCjIHsrOQZlOeE+dUDjAaqo=
